name = "Cozy-Workshop"
author = "Neocky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7689b547cf8d33b3a3863d00faaf0448b1e2e935d8a815e3688435dde2b921ee"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
