name = "Cozy-Workshop"
author = "Neocky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8987f16ccd5a2f12d5afbdde9c5ed40af4fc643cbccb614b9b2c342ec85fc8be"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
