name = "Cozy-Workshop"
author = "Neocky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5a41f10457f5222db57d2eef0c12f7bd6f8fc8e25e435214990008a34bdf5ca"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
