name = "Cozy-Workshop"
author = "Neocky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "29fc1898ac0199e7471c2b344da72090306f761ed308e78ae0ed1f308c748aff"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
