name = "Cozy-Workshop"
author = "Neocky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "389199315e2178a00f849101538461031207df35351516d16551aad3ca35afa5"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
