name = "Cozy-Workshop"
author = "Neocky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b856508c4682f81a6f4f533ce6500b5f0603804e445eaf2f7e554b60dec2c5a"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
