name = "Cozy-Workshop"
author = "Neocky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4278b71ef60ea9e0e3e4a805b8c657b8037b2274395a896e28a37f99c65fecde"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
