name = "Cozy-Workshop"
author = "Neocky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9aaa9719765e2e4b9714f25631d137608e20e6f8531ee7575d1d07ccff612142"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
