name = "Cozy-Workshop"
author = "Neocky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d0e6520bd35ad37348f241e5bd5bd3fbc36d83166994e1b9bb8e51dcd033bb7"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
