name = "Cozy-Workshop"
author = "Neocky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee608f20796e3d22088eca7173e57b18cb22619e6902b2757a58a3a19107484a"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
