name = "Cozy-Workshop"
author = "Neocky"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bae3d61d7f400b61a0612eb4993f87bfb8e045fc4f8c15b4caa1f99abd5e3df6"

[versions]
forge = "47.2.17"
minecraft = "1.20.1"
